-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            passes = 3,
            size = 2,
            vibrancy_darkness = 0.1,
            xray = true,
        },
        rounding = 4,
    },
    ecosystem = {
        no_donation_nag = true,
        no_update_news = true,
    },
    general = {
        allow_tearing = true,
        gaps_in = 2,
        layout = "dwindle",
    },
})

-- Bezier curves
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.0}, {0.35, 1.0} } })

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 3.5,
    bezier = "easeInOutCubic",
    style = "slide",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 3.5,
    bezier = "easeInOutCubic",
    style = "slide",
})

-- Layer rules
hl.layer_rule({
    name = "Rofi layer rules",
    match = {
        namespace = "rofi",
    },
    blur = true,
})
