general {
    hide_cursor = true
    grace = 1
    disable_loading_bar = true
}

background {
    monitor =
    path = screenshot

    blur_passes = 4
    blur_size = 8

    brightness = 0.55
    contrast = 1.15
    vibrancy = 0.25
    noise = 0.01
}

label {
    monitor =
    text = 
    color = rgba(137, 180, 250, 1.0)
    font_size = 56
    font_family = JetBrainsMono Nerd Font

    position = 0, 210
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(205, 214, 244, 1.0)
    font_size = 86
    font_family = JetBrainsMono Nerd Font

    position = 0, 105
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B")"
    color = rgba(186, 194, 222, 1.0)
    font_size = 22
    font_family = JetBrainsMono Nerd Font

    position = 0, 25
    halign = center
    valign = center
}

label {
    monitor =
    text = Welcome back, Yegor
    color = rgba(166, 173, 200, 1.0)
    font_size = 18
    font_family = JetBrainsMono Nerd Font

    position = 0, -30
    halign = center
    valign = center
}

input-field {
    monitor =

    size = 240, 40
    outline_thickness = 1

    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true
    rounding = -1

    outer_color = rgba(137, 180, 250, 1.0)
    inner_color = rgba(30, 30, 46, 0.3)
    font_color = rgba(205, 214, 244, 1.0)

    check_color = rgba(249, 226, 175, 1.0)
    fail_color = rgba(243, 139, 168, 1.0)

    font_family = JetBrainsMono Nerd Font
    fade_on_empty = false
    placeholder_text = Password
    fail_text = Wrong password

    position = 0, -115
    halign = center
    valign = center
}
