format = """
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$line_break\
$character
"""

add_newline = true

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold red"

[cmd_duration]
min_time = 500
format = "[⏱ $duration]($style)"
style = "yellow"

[fill]
symbol = " "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold blue)"
